### ISSUE TITLE
Support single-precision floating point numbers

### ISSUE THREAD

**Issue by jnbt** [neopoly/rubyfox-sfsobject#3]
* Ruby doesn't have a distinction between single and double precision floating point numbers

    > Float objects represent inexact real numbers using the native architecture's double-precision floating point representation.
    > [Source](https://ruby-doc.org/core-2.4.0/Float.html)

* Smartfox supports multiple platforms for clients. Most of them support a distinction between single- and double-precision floating point numbers.

* In my eyes the terms "float" and "double" are set for single- and double precision floating point numbers, even if IEEE 754 doesn't clearly define the terms. It is a very Ruby specific to handle every floating point number as instance of the `Float` class.

**I suggest the following changes:**

1. `Bulk` should at least handle the deserialization of `FLOAT` via [`TO_HASH`](https://github.com/neopoly/rubyfox-sfsobject/blob/195ffe14aa1a6977a44010d162edc4f36ac812c8/lib/rubyfox/sfsobject/bulk.rb#L38)
2. When using a `Schema` there should be a possibility or fallback to read a single-precision floating point number and to force-write a Ruby `Float` to a Smartfox single precision float.

**Comment by splattael** [comment]
@jnbt Thanks for reporting :+1: 

It has been fixed in via #4 :sparkles:
